# tasks/facts.yml

- name: Include os_family vars
  include_vars: Debian.yml
  when: ansible_os_family == "Debian"

# Check required variables for valid values
- name: Check monit_config_dir
  fail:
    msg: |
      Invalid value for 'monit_config_dir': {{ monit_config_dir }}

      Supported types  : String
      Supported values : Any non-null string
  when: >-
    monit_config_dir is not string
    or monit_config_dir == 0

- name: Check monitored_services
  fail:
    msg: |
      Invalid value for 'monitored_services': {{ monitored_services }}

      Supported types  : List, String
      Supported values : Any non-null list or string
  when: >-
    monitored_services is not iterable
    or monitored_services == 0

# Remove service from list of monitored_services if not part of playbook
- name: Remove nonexistent services
  set_fact:
    monitored_services: "{{ monitored_services | difference([item]) }}"
  when: >-
    item.var_name not in vars
    or lookup('vars', item.var_name) is not string
    or lookup('vars', item.var_name) == 0
  loop: "{{ monitored_services }}"

- name: Check variable 'systemd_restart_setting'
  fail:
    msg: |
      Invalid value for variable 'systemd_restart_setting': '{{ systemd_restart_setting }}'

      Supported types  : String
      Supported values : "no", "on-success", "on-failure", "on-abnormal",
                         "on-watchdog", "on-abort", "always"
  failed_when: >-
    systemd_restart_setting not in
    ['no', 'on-success', 'on-failure', 'on-abnormal',
    'on-watchdog', 'on-abort', 'always']
    or systemd_restart_setting is not string
    or systemd_restart_setting == 0
  when: >-
    (monit_systemd_restart is defined
    and monit_systemd_restart)
    or (systemd_restart is defined
    and systemd_restart)
