# tasks/main.yml

- name: Include facts
  ansible.builtin.include_tasks: facts.yml

- name: (CentOS) Install epel-release packages
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: (Debian 10) Add backports repo
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: present
    filename: stretch
    update_cache: true
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "10"

- name: Install Monit packages
  ansible.builtin.package:
    name: monit
    state: present

- name: Include systemd restart configuation
  ansible.builtin.include_tasks: systemd.yml
  when: >-
    ( monit_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

- name: Start and enable Monit service
  ansible.builtin.service:
    name: monit
    state: started
    enabled: true

- name: Install Monit config
  ansible.builtin.template:
    src: etc/monitrc
    dest: "{{ monit_config_file }}"
    owner: root
    group: root
    mode: "0600"
  notify: Restart monit

- name: Install service configs
  ansible.builtin.template:
    src: services/{{ item.daemon_name }}
    dest: "{{ monit_config_dir }}/{{ item.daemon_name }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ monitored_services }}"
  notify: Restart monit
