# tasks/main.yml

- name: Include facts
  include: facts.yml

- name: (CentOS) Install epel-release packages
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: (Debian 10) Add backports repo
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: present
    filename: stretch
    update_cache: true
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "10"

- name: Install Monit packages
  package:
    name: monit
    state: present
    
- name: Install Monit Prometheus Exporter
  package:
    name: imh-monit-prometheus
    state: present

- name: Include systemd restart configuation
  include: systemd.yml
  when: >-
    ( monit_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

- name: Start and enable Monit service
  service:
    name: monit
    state: started
    enabled: true

- name: Install Monit config
  template:
    src: monitrc
    dest: "{{ monit_config_dir }}/monitrc"
    owner: root
    group: root
    mode: 0644
  notify: restart monit

- name: Install service configs
  template:
    src: services/{{ item.daemon_name }}
    dest: "{{ monit_config_dir }}/{{ item.daemon_name }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ monitored_services }}"
  notify: restart monit
